export const CHARACTERS = [
  {"id": "learned-wo", "hanzi": "我", "pinyin": "wǒ", "meaning": "I; me", "level": "Learned", "en": "I; me", "jp": "私（わたし）", "tr": "ben"},
  {"id": "learned-ni", "hanzi": "你", "pinyin": "nǐ", "meaning": "you", "level": "Learned", "en": "you", "jp": "あなた", "tr": "sen"},
  {"id": "learned-hao", "hanzi": "好", "pinyin": "hǎo", "meaning": "good; well", "level": "Learned", "en": "good; well", "jp": "いい; 良い", "tr": "iyi; güzel"},
  {"id": "learned-shi", "hanzi": "是", "pinyin": "shì", "meaning": "to be", "level": "Learned", "en": "to be", "jp": "～です; ～である", "tr": "olmak; -dir"},
  {"id": "learned-xuesheng", "hanzi": "学生", "pinyin": "xuéshēng", "meaning": "student", "level": "Learned", "en": "student", "jp": "学生（がくせい）", "tr": "öğrenci"},
  {"id": "learned-ta-he", "hanzi": "他", "pinyin": "tā", "meaning": "he; him", "level": "Learned", "en": "he; him", "jp": "彼（かれ）", "tr": "o; onu (erkek)"},
  {"id": "learned-ta-she", "hanzi": "她", "pinyin": "tā", "meaning": "she; her", "level": "Learned", "en": "she; her", "jp": "彼女（かのじょ）", "tr": "o; onu (kadın)"},
  {"id": "learned-laoshi", "hanzi": "老师", "pinyin": "lǎoshī", "meaning": "teacher", "level": "Learned", "en": "teacher", "jp": "先生（せんせい）", "tr": "öğretmen"},
  {"id": "learned-lao", "hanzi": "老", "pinyin": "lǎo", "meaning": "old", "level": "Learned", "en": "old", "jp": "老（ろう）", "tr": "yaşlı; eski"},
  {"id": "learned-shi", "hanzi": "师", "pinyin": "shī", "meaning": "teacher; master", "level": "Learned", "en": "teacher; master", "jp": "師（し）", "tr": "öğretmen; usta"},
  {"id": "learned-women", "hanzi": "我们", "pinyin": "wǒmen", "meaning": "we; us", "level": "Learned", "en": "we; us", "jp": "私たち（わたしたち）", "tr": "biz; bizi"},
  {"id": "hsk1-05", "hanzi": "的", "pinyin": "de", "meaning": "possessive particle", "level": "HSK 1", "en": "possessive particle", "jp": "～の（所有）", "tr": "aitlik edatı"},
  {"id": "hsk1-06", "hanzi": "不", "pinyin": "bù", "meaning": "not", "level": "HSK 1", "en": "not", "jp": "～ない", "tr": "değil; -me/-ma"},
  {"id": "hsk1-07", "hanzi": "了", "pinyin": "le", "meaning": "completed action", "level": "HSK 1", "en": "completed action", "jp": "completed action", "tr": "completed action"},
  {"id": "hsk1-08", "hanzi": "人", "pinyin": "rén", "meaning": "person; people", "level": "HSK 1", "en": "person; people", "jp": "人（ひと）", "tr": "insan; kişi"},
  {"id": "hsk1-09", "hanzi": "们", "pinyin": "men", "meaning": "plural marker", "level": "HSK 1", "en": "plural marker", "jp": "複数を表す接尾辞", "tr": "çoğul eki"},
  {"id": "hsk1-10", "hanzi": "有", "pinyin": "yǒu", "meaning": "to have", "level": "HSK 1", "en": "to have; there is/are", "jp": "ある; 持っている", "tr": "sahip olmak; var"},
  {"id": "hsk1-11", "hanzi": "这", "pinyin": "zhè", "meaning": "this", "level": "HSK 1", "en": "this", "jp": "これ; この", "tr": "bu"},
  {"id": "hsk1-12", "hanzi": "那", "pinyin": "nà", "meaning": "that", "level": "HSK 1", "en": "that", "jp": "それ; あれ; その", "tr": "şu; o"},
  {"id": "hsk1-13", "hanzi": "个", "pinyin": "gè", "meaning": "general measure word", "level": "HSK 1", "en": "general measure word", "jp": "general measure word", "tr": "general measure word"},
  {"id": "hsk1-14", "hanzi": "来", "pinyin": "lái", "meaning": "to come", "level": "HSK 1", "en": "to come", "jp": "来る（くる）", "tr": "gelmek"},
  {"id": "hsk1-15", "hanzi": "去", "pinyin": "qù", "meaning": "to go", "level": "HSK 1", "en": "to go", "jp": "行く（いく）", "tr": "gitmek"},
  {"id": "hsk1-16", "hanzi": "在", "pinyin": "zài", "meaning": "at; in; to be at", "level": "HSK 1", "en": "at; in; to be at", "jp": "～にいる; ～にある", "tr": "-de/-da bulunmak"},
  {"id": "hsk1-17", "hanzi": "会", "pinyin": "huì", "meaning": "can; will; meeting", "level": "HSK 1", "en": "can; will", "jp": "できる; ～するだろう", "tr": "-ebilmek; olacak"},
  {"id": "hsk1-18", "hanzi": "说", "pinyin": "shuō", "meaning": "to speak; to say", "level": "HSK 1", "en": "to speak; to say", "jp": "話す; 言う", "tr": "konuşmak; söylemek"},
  {"id": "hsk1-19", "hanzi": "看", "pinyin": "kàn", "meaning": "to look; to see", "level": "HSK 1", "en": "to look; to see", "jp": "見る（みる）", "tr": "bakmak; görmek"},
  {"id": "hsk1-20", "hanzi": "听", "pinyin": "tīng", "meaning": "to listen", "level": "HSK 1", "en": "to listen; to hear", "jp": "聞く（きく）", "tr": "dinlemek; duymak"},
  {"id": "hsk1-21", "hanzi": "吃", "pinyin": "chī", "meaning": "to eat", "level": "HSK 1", "en": "to eat", "jp": "食べる（たべる）", "tr": "yemek"},
  {"id": "hsk1-22", "hanzi": "喝", "pinyin": "hē", "meaning": "to drink", "level": "HSK 1", "en": "to drink", "jp": "飲む（のむ）", "tr": "içmek"},
  {"id": "hsk1-23", "hanzi": "水", "pinyin": "shuǐ", "meaning": "water", "level": "HSK 1", "en": "water", "jp": "水（みず）", "tr": "su"},
  {"id": "hsk1-24", "hanzi": "茶", "pinyin": "chá", "meaning": "tea", "level": "HSK 1", "en": "tea", "jp": "お茶（おちゃ）", "tr": "çay"},
  {"id": "hsk1-25", "hanzi": "饭", "pinyin": "fàn", "meaning": "rice; meal", "level": "HSK 1", "en": "rice; meal", "jp": "ご飯（ごはん）", "tr": "pilav; yemek"},
  {"id": "hsk1-26", "hanzi": "天", "pinyin": "tiān", "meaning": "day; sky", "level": "HSK 1", "en": "day; sky", "jp": "日; 空", "tr": "gün; gökyüzü"},
  {"id": "hsk1-27", "hanzi": "年", "pinyin": "nián", "meaning": "year", "level": "HSK 1", "en": "year", "jp": "年（とし）", "tr": "yıl"},
  {"id": "hsk1-28", "hanzi": "月", "pinyin": "yuè", "meaning": "month; moon", "level": "HSK 1", "en": "month; moon", "jp": "月（つき）", "tr": "ay"},
  {"id": "hsk1-29", "hanzi": "日", "pinyin": "rì", "meaning": "sun; day", "level": "HSK 1", "en": "sun; day", "jp": "日（ひ／にち）", "tr": "güneş; gün"},
  {"id": "hsk1-30", "hanzi": "今", "pinyin": "jīn", "meaning": "now; today (as in 今天)", "level": "HSK 1", "en": "now; today", "jp": "今（いま）", "tr": "şimdi; bugün"},
  {"id": "hsk1-31", "hanzi": "明", "pinyin": "míng", "meaning": "bright; tomorrow (明天)", "level": "HSK 1", "en": "bright; tomorrow", "jp": "明るい; 明日", "tr": "parlak; yarın"},
  {"id": "hsk1-32", "hanzi": "昨", "pinyin": "zuó", "meaning": "yesterday (昨天)", "level": "HSK 1", "en": "yesterday", "jp": "昨日（きのう）", "tr": "dün"},
  {"id": "hsk1-33", "hanzi": "时", "pinyin": "shí", "meaning": "time", "level": "HSK 1", "en": "time", "jp": "時（とき）", "tr": "zaman; saat"},
  {"id": "hsk1-34", "hanzi": "候", "pinyin": "hòu", "meaning": "time; wait (时候)", "level": "HSK 1", "en": "time; wait (时候)", "jp": "time; wait (时候)", "tr": "time; wait (时候)"},
  {"id": "hsk1-35", "hanzi": "现", "pinyin": "xiàn", "meaning": "now; current (现在)", "level": "HSK 1", "en": "now; current (现在)", "jp": "now; current (现在)", "tr": "now; current (现在)"},
  {"id": "hsk1-36", "hanzi": "家", "pinyin": "jiā", "meaning": "home; family", "level": "HSK 1", "en": "home; family", "jp": "家; 家族", "tr": "ev; aile"},
  {"id": "hsk1-37", "hanzi": "学", "pinyin": "xué", "meaning": "to study", "level": "HSK 1", "en": "to study", "jp": "学ぶ（まなぶ）", "tr": "öğrenmek; çalışmak"},
  {"id": "hsk1-38", "hanzi": "校", "pinyin": "xiào", "meaning": "school (学校)", "level": "HSK 1", "en": "school", "jp": "学校（がっこう）", "tr": "okul"},
  {"id": "hsk1-41", "hanzi": "同", "pinyin": "tóng", "meaning": "same; together (同学)", "level": "HSK 1", "en": "same; together (同学)", "jp": "same; together (同学)", "tr": "same; together (同学)"},
  {"id": "hsk1-42", "hanzi": "朋", "pinyin": "péng", "meaning": "friend (朋友)", "level": "HSK 1", "en": "friend (朋友)", "jp": "friend (朋友)", "tr": "friend (朋友)"},
  {"id": "hsk1-43", "hanzi": "友", "pinyin": "yǒu", "meaning": "friend", "level": "HSK 1", "en": "friend", "jp": "友（とも）; 友達", "tr": "arkadaş"},
  {"id": "hsk1-44", "hanzi": "爱", "pinyin": "ài", "meaning": "to love", "level": "HSK 1", "en": "to love", "jp": "愛する", "tr": "sevmek"},
  {"id": "hsk1-45", "hanzi": "喜", "pinyin": "xǐ", "meaning": "to like (喜欢)", "level": "HSK 1", "en": "to like; to be happy", "jp": "喜ぶ", "tr": "sevmek; mutlu olmak"},
  {"id": "hsk1-46", "hanzi": "欢", "pinyin": "huān", "meaning": "happy; like", "level": "HSK 1", "en": "happy; like", "jp": "happy; like", "tr": "happy; like"},
  {"id": "hsk1-47", "hanzi": "大", "pinyin": "dà", "meaning": "big", "level": "HSK 1", "en": "big", "jp": "大きい", "tr": "büyük"},
  {"id": "hsk1-48", "hanzi": "小", "pinyin": "xiǎo", "meaning": "small", "level": "HSK 1", "en": "small", "jp": "小さい", "tr": "küçük"},
  {"id": "hsk1-49", "hanzi": "多", "pinyin": "duō", "meaning": "many; much", "level": "HSK 1", "en": "many; much", "jp": "多い", "tr": "çok"},
  {"id": "hsk1-50", "hanzi": "少", "pinyin": "shǎo", "meaning": "few; little", "level": "HSK 1", "en": "few; little", "jp": "少ない", "tr": "az"},
  {"id": "hsk1-51", "hanzi": "很", "pinyin": "hěn", "meaning": "very", "level": "HSK 1", "en": "very", "jp": "とても", "tr": "çok; oldukça"},
  {"id": "hsk1-52", "hanzi": "太", "pinyin": "tài", "meaning": "too; extremely", "level": "HSK 1", "en": "too; extremely", "jp": "too; extremely", "tr": "too; extremely"},
  {"id": "hsk1-53", "hanzi": "和", "pinyin": "hé", "meaning": "and; with", "level": "HSK 1", "en": "and; with", "jp": "～と", "tr": "ve; ile"},
  {"id": "hsk1-54", "hanzi": "也", "pinyin": "yě", "meaning": "also", "level": "HSK 1", "en": "also", "jp": "～も", "tr": "de/da; ayrıca"},
  {"id": "hsk1-55", "hanzi": "吗", "pinyin": "ma", "meaning": "question particle", "level": "HSK 1", "en": "question particle", "jp": "疑問の助詞「か」", "tr": "soru edatı"},
  {"id": "hsk1-56", "hanzi": "呢", "pinyin": "ne", "meaning": "question particle", "level": "HSK 1", "en": "question particle", "jp": "疑問・話題提示の助詞", "tr": "soru/konu edatı"},
  {"id": "hsk1-57", "hanzi": "请", "pinyin": "qǐng", "meaning": "please; to invite", "level": "HSK 1", "en": "please; to invite", "jp": "お願いします; 招待する", "tr": "lütfen; davet etmek"},
  {"id": "hsk1-58", "hanzi": "谢", "pinyin": "xiè", "meaning": "to thank", "level": "HSK 1", "en": "to thank", "jp": "感謝する", "tr": "teşekkür etmek"},
  {"id": "hsk1-59", "hanzi": "对", "pinyin": "duì", "meaning": "correct; toward", "level": "HSK 1", "en": "correct; toward", "jp": "正しい; ～に対して", "tr": "doğru; -e/-a karşı"},
  {"id": "hsk1-60", "hanzi": "起", "pinyin": "qǐ", "meaning": "to rise; together (一起)", "level": "HSK 1", "en": "to rise; together (一起)", "jp": "to rise; together (一起)", "tr": "to rise; together (一起)"},
  {"id": "hsk1-61", "hanzi": "再", "pinyin": "zài", "meaning": "again", "level": "HSK 1", "en": "again", "jp": "もう一度", "tr": "tekrar"},
  {"id": "hsk1-62", "hanzi": "见", "pinyin": "jiàn", "meaning": "to see; to meet", "level": "HSK 1", "en": "to see; to meet", "jp": "見る; 会う", "tr": "görmek; buluşmak"},
  {"id": "hsk1-63", "hanzi": "买", "pinyin": "mǎi", "meaning": "to buy", "level": "HSK 1", "en": "to buy", "jp": "買う", "tr": "satın almak"},
  {"id": "hsk1-64", "hanzi": "钱", "pinyin": "qián", "meaning": "money", "level": "HSK 1", "en": "money", "jp": "お金", "tr": "para"},
  {"id": "hsk1-65", "hanzi": "块", "pinyin": "kuài", "meaning": "yuan (money); piece", "level": "HSK 1", "en": "yuan (money); piece", "jp": "yuan (money); piece", "tr": "yuan (money); piece"},
  {"id": "hsk1-66", "hanzi": "车", "pinyin": "chē", "meaning": "car; vehicle", "level": "HSK 1", "en": "car; vehicle", "jp": "車", "tr": "araba; araç"},
  {"id": "hsk1-67", "hanzi": "飞", "pinyin": "fēi", "meaning": "to fly", "level": "HSK 1", "en": "to fly", "jp": "飛ぶ", "tr": "uçmak"},
  {"id": "hsk1-68", "hanzi": "机", "pinyin": "jī", "meaning": "machine (飞机)", "level": "HSK 1", "en": "machine (飞机)", "jp": "machine (飞机)", "tr": "machine (飞机)"},
  {"id": "hsk1-69", "hanzi": "电", "pinyin": "diàn", "meaning": "electricity (电脑)", "level": "HSK 1", "en": "electricity (电脑)", "jp": "electricity (电脑)", "tr": "electricity (电脑)"},
  {"id": "hsk1-70", "hanzi": "话", "pinyin": "huà", "meaning": "speech; language", "level": "HSK 1", "en": "speech; language", "jp": "話; 言葉", "tr": "söz; konuşma"},
  {"id": "hsk1-71", "hanzi": "书", "pinyin": "shū", "meaning": "book", "level": "HSK 1", "en": "book", "jp": "本", "tr": "kitap"},
  {"id": "hsk1-72", "hanzi": "字", "pinyin": "zì", "meaning": "character; word", "level": "HSK 1", "en": "character; written word", "jp": "字", "tr": "karakter; yazı"},
  {"id": "hsk1-73", "hanzi": "中", "pinyin": "zhōng", "meaning": "middle; China (中国)", "level": "HSK 1", "en": "middle; China", "jp": "中; 中国", "tr": "orta; Çin"},
  {"id": "hsk1-74", "hanzi": "国", "pinyin": "guó", "meaning": "country", "level": "HSK 1", "en": "country", "jp": "国", "tr": "ülke"},
  {"id": "hsk1-75", "hanzi": "汉", "pinyin": "hàn", "meaning": "Chinese (汉语)", "level": "HSK 1", "en": "Chinese (汉语)", "jp": "Chinese (汉语)", "tr": "Chinese (汉语)"},
  {"id": "hsk1-76", "hanzi": "语", "pinyin": "yǔ", "meaning": "language", "level": "HSK 1", "en": "language", "jp": "語; 言語", "tr": "dil"},
  {"id": "hsk1-77", "hanzi": "英", "pinyin": "yīng", "meaning": "English (英语)", "level": "HSK 1", "en": "English", "jp": "英語", "tr": "İngilizce"},
  {"id": "hsk1-78", "hanzi": "上", "pinyin": "shàng", "meaning": "up; on; previous", "level": "HSK 1", "en": "up; on; previous", "jp": "上", "tr": "üst; yukarı; önceki"},
  {"id": "hsk1-79", "hanzi": "下", "pinyin": "xià", "meaning": "down; below; next", "level": "HSK 1", "en": "down; below; next", "jp": "下", "tr": "alt; aşağı; sonraki"},
  {"id": "hsk1-80", "hanzi": "前", "pinyin": "qián", "meaning": "front; before", "level": "HSK 1", "en": "front; before", "jp": "前", "tr": "ön; önce"},
  {"id": "hsk2-01", "hanzi": "知", "pinyin": "zhī", "meaning": "to know (知道)", "level": "HSK 2", "en": "to know", "jp": "知る", "tr": "bilmek"},
  {"id": "hsk2-02", "hanzi": "道", "pinyin": "dào", "meaning": "way; to know", "level": "HSK 2", "en": "way; road", "jp": "道", "tr": "yol"},
  {"id": "hsk2-03", "hanzi": "觉", "pinyin": "jué", "meaning": "to feel (觉得)", "level": "HSK 2", "en": "to feel (觉得)", "jp": "to feel (觉得)", "tr": "to feel (觉得)"},
  {"id": "hsk2-04", "hanzi": "得", "pinyin": "de", "meaning": "structural particle; to get", "level": "HSK 2", "en": "structural particle; to get", "jp": "structural particle; to get", "tr": "structural particle; to get"},
  {"id": "hsk2-05", "hanzi": "思", "pinyin": "sī", "meaning": "to think (意思)", "level": "HSK 2", "en": "to think", "jp": "思う", "tr": "düşünmek"},
  {"id": "hsk2-06", "hanzi": "因", "pinyin": "yīn", "meaning": "because (因为)", "level": "HSK 2", "en": "because (因为)", "jp": "because (因为)", "tr": "because (因为)"},
  {"id": "hsk2-07", "hanzi": "为", "pinyin": "wèi", "meaning": "for; because", "level": "HSK 2", "en": "for; because", "jp": "for; because", "tr": "for; because"},
  {"id": "hsk2-08", "hanzi": "所", "pinyin": "suǒ", "meaning": "place; so (所以)", "level": "HSK 2", "en": "place; so (所以)", "jp": "place; so (所以)", "tr": "place; so (所以)"},
  {"id": "hsk2-09", "hanzi": "以", "pinyin": "yǐ", "meaning": "with; so", "level": "HSK 2", "en": "with; so", "jp": "with; so", "tr": "with; so"},
  {"id": "hsk2-10", "hanzi": "但", "pinyin": "dàn", "meaning": "but (但是)", "level": "HSK 2", "en": "but (但是)", "jp": "but (但是)", "tr": "but (但是)"},
  {"id": "hsk2-11", "hanzi": "虽", "pinyin": "suī", "meaning": "although (虽然)", "level": "HSK 2", "en": "although (虽然)", "jp": "although (虽然)", "tr": "although (虽然)"},
  {"id": "hsk2-12", "hanzi": "然", "pinyin": "rán", "meaning": "so; however", "level": "HSK 2", "en": "so; however", "jp": "so; however", "tr": "so; however"},
  {"id": "hsk2-13", "hanzi": "还", "pinyin": "hái", "meaning": "still; also", "level": "HSK 2", "en": "still; also", "jp": "still; also", "tr": "still; also"},
  {"id": "hsk2-14", "hanzi": "最", "pinyin": "zuì", "meaning": "most", "level": "HSK 2", "en": "most", "jp": "most", "tr": "most"},
  {"id": "hsk2-15", "hanzi": "比", "pinyin": "bǐ", "meaning": "to compare", "level": "HSK 2", "en": "to compare", "jp": "to compare", "tr": "to compare"},
  {"id": "hsk2-16", "hanzi": "真", "pinyin": "zhēn", "meaning": "really; true", "level": "HSK 2", "en": "really; true", "jp": "本当; 真の", "tr": "gerçekten; doğru"},
  {"id": "hsk2-17", "hanzi": "快", "pinyin": "kuài", "meaning": "fast; soon", "level": "HSK 2", "en": "fast; pleasant", "jp": "速い; 快い", "tr": "hızlı; hoş"},
  {"id": "hsk2-18", "hanzi": "慢", "pinyin": "màn", "meaning": "slow", "level": "HSK 2", "en": "slow", "jp": "遅い", "tr": "yavaş"},
  {"id": "hsk2-19", "hanzi": "高", "pinyin": "gāo", "meaning": "tall; high", "level": "HSK 2", "en": "tall; high; expensive", "jp": "高い", "tr": "uzun; yüksek; pahalı"},
  {"id": "hsk2-20", "hanzi": "新", "pinyin": "xīn", "meaning": "new", "level": "HSK 2", "en": "new", "jp": "新しい", "tr": "yeni"},
];
